#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/walls/4.jpg &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zathura state=tiled
bspc rule -a zoom state=floating
